const eventList = [
  {
    name: 'name',
    description: 'orlando jam',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'Event1',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'jam 2',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'name',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'florida',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'Test Event 3',
    description: 'orlando Jam',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'name',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'name',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'name',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'name',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  },
  {
    name: 'name',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
  }
]

export default eventList;