const eventList = [
  {
    name: 'name',
    description: 'orlando jam',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: 28.5383,
    lng: -81.3792,
  },
  {
    name: 'Event1',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: -23,
    lng: 50
  },
  {
    name: 'jam 2',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: 50,
    lng: -80
  },
  {
    name: 'name2',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'florida',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: 21,
    lng: 22
  },
  {
    name: 'Test Event 3',
    description: 'orlando Jam',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: 53,
    lng: -90
  },
  {
    name: 'name3',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: -60,
    lng: 40
  },
  {
    name: 'name4',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: 34.06816112517546,
    lng: -118.44554252766474
  },
  {
    name: 'name5',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: 60,
    lng: 70
  },
  {
    name: 'name6',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: 60,
    lng: 45
  },
  {
    name: 'name7',
    description: 'description',
    date: 'date',
    address: 'address',
    city: 'city',
    state: 'state',
    country: 'country',
    zip: 'zip',
    jam: true,
    gym: true,
    lat: 60,
    lng: 41
  }
]

export default eventList;